* A Game On Your Wishlist is on Sale
Thoughts on perpetually growing game libraries.

Steam and Humble Bundle sales, among others, are almost persistent
nowadays. The success of pay-what-you-want and regular discounts has
certainly been beneficial to the games industry. It has also provided
almost innumerable games to consumers. This in itself is not an issue,
where problems arise is the management of the game libraries that
result. 

As a reminder games, as software, are typically sold as licenses
rather than as owned products. They can not be traded, they are
(broadly speaking) perpetual, and so they remain. When this is coupled
with regular sales, what is the result? A steadily increasing games
library. Depending on the user, this could be a slow growth, remaining
under a hundred games for a number of years, but the ease of getting
new games from Steam sales and Humble Bundles (of which the majority
can be registered on Steam), means that games libraries can, and will, grow.

Now consider a user wishing to play a game. The majority of effort on
Steam has gone into discovery of new games, improving the store,
providing a wishlist and so on. There has been relatively little work
done on dealing with the games a user already owns. 

This would appear to not be that much of an issue. Steam provides a
list of games that you own, why should that not be adequate?
Certainly, for the majority of users at this time, a search feature,
tags, and favourites are sufficient. At what size of library do these
organizational features become insufficient? 100? 200? 600?

It may be easy to keep track of a couple of hundred games, but when
the number approaches 600 (an arbitrary number chosen for no other
reason than that is the size of my own games library, and so I speak
from personal experience) issues do arise. Organisation by
'favourites' no longer work as a favourite's list can easily be a
couple of hundred games. Organisation by tags can be useful, but a
list looses all meaning when it is too long, and manual categorisation
of 600 items is not particularly enjoyable. Search is only useful if
you are trying to find a specific item in a list, which requires the
user to be able to remember or know beforehand the game they wish to
play. 

Another, and potentially crucial, filtering technique is to go by what
games are installed. However, with the desire to play games instantly,
and the reduction in cost of storage media, there is no difficulty in
having 300 games installed at any one time. It would appear then, that
as game libraries grow, they require more advanced ways of exploring
the data to provide a user with useful information to enable game
playing choices.


** The Capabilities of Steam as a game library.

Steam tracks certain information. Achievements are the most obvious,
though it also tracks total play time, recent play time, games that
friends play. Yet these are under-utilised in the information foraging
behaviours that occur when sorting through games.

If Steam is to watch over our playing, and link and network us, we
should use that information and have access to it. The Steam Store
meanwhile has facilities for user generated tags of games, but oddly
does not allow exploration of a users own game library by those tags.

This is not a problem with game discovery as a whole, in the way that
some work has focused on (Ryan and Kaltman), instead it is a problem
of personalised data display of owned games. 

** Enter MetaSteam

MetaSteam, as a python backend with web visualisations, is an attempt
to deal with the problems raised. It scans for installed steam games
on a computer, compares that with a users online profile, and extracts
Store page tags to associate with each game. It then provides a number
of visualisations, customised to the user, of their games using d3 for
them to explore.

The visualisations provided or intended include:
1) Displays of Store page tag groups (circle packed by number of games in a group)
2) Displays of a set of games, packed by the number of hours played in each game
3) Displays of timelines of genres. 



