* Phenomenological psychology notes

** Temporality

p30- Dasein:
Projecting itself towards future possibilities. 
Existence is not a noun, but a verb.

Facticity:
limits upon our choices to create ourselves.

Mood: pre-reflective way of experiencing the world our experience of
the world is first and foremost lived pre-reflectively through a mood
and only later understood through reflection

Being-towards-death:
the ultimate limit to existance is death. 
We can choose how we will face the ontological givens of death.

Care: being in the world revolves around us being involved in the
world, actively engaged in other things and people. This care stands
in contrast to objects that are simply present at hand and the way
these things simply occur space rather than live in space.

Authenticity: When dasein no longer takes the world for granted but,
instead, recognizes the fundamental reality of being that is
being-towards-death.  Most of the time, dasein exists inauthentically,
hiding from the reality of being-towards-death through the security
that comes from being part of the "they"

Being-with: ie: being-in-the-world-with-others I must acknowledge my
relationship to others when i do something or use something.

Discourse: The distinction between language as a prosaic medium
designed to simply and effectively communicate information and poetic
language offering the possibility of disclosing our being in the world
becomes particularly important.


