* SIA Writings

** An introduction to SIA
*** Motivation

    Why am I doing this? Because there is a whole realm of social
    behaviours lying unused in games and social models that could be
    interesting.

*** Goal

    The goal of the work is to supplement the current social models
    CiF and Praxis the ability to deal with Socio-Institutional
    Actions.
    
    By Socio-Institutional Actions I have a very specific meaning in
    mind:
    1) Behaviours that are individually observable. Ie: To avoid the
       birds eye view of games like Civilisation, and stay focused on
       individual characters.
    2) Behaviours that are not solely focused on close friends or
       familial relations, and instead have interactions with
       individuals belonging to particular groups.
    3) Behaviours that, in their group oriented form, express the
       following structural features: 
       a) Organisation and Reasoning concerned with various
       perspectives of time (See Giddens and Schechner)
       b) Power relationships (See Levi Martin and Bourdieu)
       c) Collaborative and Ritualistic Action (See Castelfranchi and
       Schechner and [[file:argumentOverview][tribal properties]])
       d) Governance of those structures (see Fligstein)
       e) imperfect knowledge regarding identity
    4) Behaviours that are transferred and indoctrinated into agents dynamically


    # take the form of political
    # manipulation, religion, generation and arbitration of laws, or
    # philosophical thought experiments such as Rawl's Veil of
    # Ignorance. Current work, such as CiF and Praxis, are able to
    # encapsulate interpersonal interactions at a personal and familial
    # level quite impressively. They do not, however, model complex
    # structures in a dynamic way.
    # at this point, mentioning various bits of hierarchical orderings
    # of society such as mcluhan, psychological, and anthropological
    # hierarchies may be helpful

*** Research Questions

**** Description:
     Can we describe tribal and institutional behaviours in a
     reasonably authorable computational form? 

     What will happen if we layer tribal or institutional behaviours
     on top of current social models such as CiF and Praxis

     

**** Experimental:
     Can those structures be dynamically modified by the agents themselves?





**** Causal
     Can those structures be balanced into semi-stable systems
     suitable for games?



*** Simple Examples

**** Gormenghast

**** Court Society
**** Galactica

*** General Concepts

**** Time

**** Power

**** Social Action

**** Structure

*** Theory

**** General

**** Sociology


**** Anthropology

**** Philosophy

*** A Specific Focus: 'Tribal' structures

*** Computational Tribes

**** First Steps: Implementing a basic tribal grammar

**** Tribes with Social Actions

**** Self-Modifying Tribes


*** From Tribes to institutions


** Playable Tribal Structures

