* Dissertation bits and pieces
** Title Ideas
   "Uncomfortable Institutions"
** Purpose of Dissertation
   To *Answer* Questions
   To *Argue* a Position
   To *Record* Research
** Dissertation                                                                 :structure:
*** Prior Work and Context
    Sociology/ Anthropology / Ethnology
    Economics
    Critical Theory
    AI and MAS
    Computational Media

    Identification of Hole in Literature:

*** Methodology
    Phenomenology and Grounded Theory
    Inhabited Institutions
    Computational Media and code studies

    Resulting Methodology:

*** Existing in the World
    Fiction
    Non-Fiction
    Theory
    Computational

    Result: Dataset

*** Pre-formal Theory
    Analysis of existing forms and examples
    Source Code Analysis
    Grounded Theory Coding

    Result:

*** Formal Calculus
    Delegation Logic, Monads, Exclusion logic,
    Temporal Calculus etc

    Result:

*** Computational Implementation
    consideration of Cif, Versu, Rete, Neural Networks, haskell, monad transformers
    Tidal and ChuCk, Meta/Reflective towers, MOISE

    result: python layered DSL Production System, temporal, reflective, typed? modular

*** Authoring / UX Considerations
    WebShell, prior authoring programs, programming, netlogo,
    user interfaces, live coding
    emacs, spacemacs

*** Resulting Experiences
    city map, newspaper, soundscape, vault, street, bot?

    Result:

*** Rebuttal of Criticisms
    Games criticisms
    Theory criticisms
    Engineering criticisms

*** Reflection
*** Title
*** Introduction
*** Abstract
** Plans and Dissertation Structure                                             :dissertation:structure:plans:
   Interspersed with Examples:
   Games / Fiction / Anthropological

   Intro
   Background   : Institutional theory, Examples
   Background 2 : Systems and Games, Examples
   The Structure of Institutions
   The authoring of Institutions
   The modelling of Institutions
   Example Models
   Analysis and Assessment
   Discussion
   Conclusion

*** Argument
    Institutions are *structured* collections of normative rules.
    They inform all aspects of social action.
    They make for cheaper, faster, and better reperesentations to author social simulations with.
    (Better in that they can encode interactions?)

    They structure of Institutions is fluid, changing, and ill defined.
    Assistive authoring tools are required to feasibly create them (why?)

    Assessment of modelled institutions should look less at coherence and more at ... what?
    Not intelligibility or stability.

** Dissertation Chapters                                                        :structure:
*** Title
*** Introduction
**** Institutions 101
**** Problems
**** Socially Inspired Computing
**** Research Questions
**** Contributions
*** Institutional Design 101
*** Core Theory Influences
**** New Institutionalism / Field Theory
**** Activity Theory
**** Normative Multi-Agent Systems

*** General Background
**** Theories
***** Giddens
**** Media
***** Games
***** Fiction
**** Formalisms
***** Grossi
***** Evans Exclusion Logic
**** NorMAS
***** Balke
**** Sociology and Anthropology
***** Graeber
**** Authoring Tool Design
*** Theory of Institutions
**** Structure of Institutions
**** Norms and Rules
*** Institutional Analysis of Existing Media
**** Fiction
**** Games
*** Institutionally Inspired Simulations/Games
*** Architecture
**** Authoring Tool
**** Institution Sim
*** Implementations
**** Vault Sim

*** Results and Analysis

*** Conclusion
**** Future Work
*** Bibliography
