* The Social Roguelike

** Background
   https://en.wikipedia.org/wiki/Chronology_of_roguelike_video_games

*** From Rogue to modern Procedural Death Labyrinths

**** Notable Recent Roguelikes

***** FTL

***** Dungeon of the Endless

***** The Binding of Isaac

***** Rogue Legacy?

***** Stealth Inc.


*** Social Games

**** The Last Federation

**** Praxis / Versu

**** CiF / Prom Week

**** Noir Syndrome

**** Sunless Sea

**** The Wolf Among Us

**** Democracy 3

**** Tropico, Galactic Civ, Distant Worlds, Europa Universalis...

**** Dwarf Fortress, Spacebase DF-9, etc



*** Interesting Research and Work:

**** Jurafsky's work on politness,
**** Hawes work on conversational dynamics of the supreme court
**** Giddens Work on Ritual
**** Anthropology.

**** Robert Greene's 48 laws of power
     Particularly the court of Louis XIV(?). Two chosen courtiers
     bringing arguments to him, he listens, and then action is taken.


** Design
*** Components of a Roguelike
    randomly generated dungeon levels
    variable effect items
    permadeath

**** Dungeon of the Endless notes:
     looking at the simulation files there are:
     dungeon, heroe, hero_class, item, itemHero, ItemHero_class, mob
     mob_class, module, module_class, npc, room, and skill


*** What would a Social Roguelike consist of?
    Small scale social situations,
    procedurally generated
    more abstract than cif style relationships,
    power, authority of primary interest
    steadily layering the rules and situations you get yourself into on top of each other.
    Gies, ritual, tradition.

*** Possible implementations:
**** Court Politics
     see stuff like Greene, By the Sword for fencing,
     Discworld for the assassination of Winder.

**** Generative Institutions
     See discworld, red mars

**** Red Mars / FTL.
     generative society.




*** Simulation Side realisations

*** Gameplay realisations

**** Under the dome
     under the dome's particular combination of charismatic opposition, changing alliegances
