* Worked examples of institutions                                  :examples:
  In an attempt to specify particular institutions
** Annotation Structure :bourdieu:bicchieri:searle:grossi:fligstein:structure:
   Fligstein - Roles, Field, Greater Interface, Social Skill, *IGU, Crisis,
   Resolution* Searle: Brute and Institutional Facts Marx/Bourdieu: Capitals
   Grossi: Institution/Organization Bicchieri: Descriptive/Prescriptive Norms,
   Sanctions

*** Roles

*** Facts

**** Brute

**** Institutional

*** Capitals

*** Field

*** IGU

*** Sanctions

**** Legitimate

**** Illegitimate

*** Interactions

*** Norms

*** Crises

*** Organizations

** Racist Police Violence                                                       :violence:police:
   Roles: Police, Civilians

   Brute Facts: Colour of Skin, Driving Speed, Car Colour, Items in Car, State
   of Car Maintenance, Gender Institutional Facts: Desirable, Undesirable,
   Idealised, Neutral Capitals: Economic, Social, Intellectual, Trust, Fear

   Field: Police Observation -> Pull over -> Release / Escalate

   IGU: Policy Makers, Unions, Civil Rights Groups

   Legitimate Sanctions: Ticket, Warning, Arrest Illegitimate Sanctions: Slurs,
   Insults, Beating, Shooting, Rape

   Interactions: Police->Desirable/Undesirable/Idealised/Neutral/Policy Makers
   Policy Makers -> Police

   Norms: police stop group -> interact -> (NG/ID-> Behave according to
   protocol) -> (FG -> Behave leniently) -> (UG -> Behave extra judicially)

   Crises: Publicised Illegitimate Sanctions. Trust and Fear

   Organization: Police -> Hierarchical

** Street Experience                                      :experience:street:
   Roles: Police, Pedestrians, Assisted-Travellers (Motor/Device/Animal),
   Criminals, Entertainers, Shopkeepers, Children, Families, Animals, Street
   Workers, Sex Workers, Town Criers, Soldiers

   Brute Facts: Building Style, Street Size/Cleanliness, Business, Time
   Institutional Facts: ?

   Capitals: Economic, Social, Intellectual

   Field: ?

   IGU: Politicians, Guilds, Police

   Legitimate Sanctions: Illegitimate Sanctions:

   Interactions:

   Norms:

   Crises:

   Organizations:

** Albinos in Africa?                                 :magic:violence:africa:
** Tribes?                                                   :graeber:tribes:
** Libraries?                                             :library:education:
** Law-Making                                          :politics:law:society:
** Eugenics                                                :society:eugenics:
** Rituals                                            :society:tribal:ritual:
** Debt                                      :society:economics:debt:graeber:
** Slavery                                    :slavery:graeber:debt:violence:
